### PR TITLE
Bumps version.jaeger to 1.1.0

### PR DESCRIPTION
**Pull request by Nick-Anderssohn**
Addresses issue #69

### CODE REVIEW

**Comment by geoand** [comment]
LGTM. @pavolloffay is there anything specific we need to take care of with the new version?

**Comment by pavolloffay** [comment]
There shouldn't be anything special. Jaeger 1.x should support OT API 0.32.0 and 0.33.0

**Comment by geoand** [comment]
Excellent, thanks!

**Comment by Nick-Anderssohn** [comment]
Thanks for merging so fast! Do you have an idea of when the next release will be cut?

**Comment by geoand** [comment]
Not really TBH. I need to see what else is pending, if anything. Hopefully sometime next week. 
Ping me if you don't hear any news by then 😎

**Comment by Nick-Anderssohn** [comment]
Hey @geoand, any update on when this will get released?

**Comment by geoand** [comment]
Hey @Nick-Anderssohn 

I want to get #76 in as well so we can have the latest version of OpenTracing. Once that is in, I'll cut a release

**Comment by geoand** [comment]
I just released version `3.0.0`. It should be on Maven Central by tomorrow

**Comment by Nick-Anderssohn** [comment]
I see that the [cloud starter](https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-spring-cloud-starter/0.5.0) maven entry was updated, but doesn't look like [web starter](https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-spring-jaeger-web-starter) was. @geoand do you know if web starter will be updated too?

**Comment by geoand** [comment]
It looks like the package never sync from Bintray to Central. I'll check it out but I may have to do a `3.0.1`

**Pull request merged**
