### PR TITLE
Bump OT to 0.32

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@ask4gilles Could you also check and make sure this is complete?

**Comment by pavolloffay** [comment]
There is also a cloud starter which should be updated, however we don't have a release yet.

**Comment by geoand** [comment]
Ah yes! Forgot about that. I will mark this as WIP then.

**Comment by ask4gilles** [comment]
lgtm

**Comment by ask4gilles** [comment]
@geoand I think you can bump the OT java-spring-cloud to 0.3.0 now, thx!

**Comment by geoand** [comment]
@ask4gilles, @pavolloffay OK to merge?

**Comment by ask4gilles** [comment]
@geoand LGTM

**Pull request merged**
