### PR TITLE
Bumped Opentracing web starter version to 3.0.1

### PR DESCRIPTION
**Pull request by davebarda**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

I'll have to take a closer look at the dependency try to make sure all the dependencies that use OpenTracing use the proper version.

**Comment by davebarda** [comment]
Cool, thanks!

**Comment by geoand** [comment]
Sorry I haven't looked at this yet, hopefully within the next few days

**Comment by davebarda** [comment]
Thanks, waiting for it :)

**Comment by geoand** [comment]
@davebarda would you mind rebasing your PR onto the latest master?

I would like CI to verify this work along with #77 that went in

**Comment by davebarda** [comment]
Done

**Comment by geoand** [comment]
LGTM, thanks!

**Pull request merged**
